"""
Every field the supplier's API document names, and where each can be found.

Generated from the document's own field tables, not retyped: the text of
api_english.pdf was parsed, two misfiled sections were corrected (queryOrderStatus
lists its response fields under "Request Fields"; updatePrintImage's line fields
follow its goodsList), and what the live API returns without documenting it was
added and marked as observed.

Regenerate rather than edit by hand.
"""

from __future__ import annotations

#: Order-level fields of a placeOrder body, as documented.
PLACE_ORDER_FIELDS: tuple[str, ...] = ('platformType',
 'sourcePlatformOid',
 'platformOrderStatus',
 'platformRefundStatus',
 'platformOid',
 'consigneeName',
 'phone',
 'address',
 'addressOptional',
 'receiverCountry',
 'receiverProvince',
 'receiverCity',
 'receiverDistrict',
 'receiverTown',
 'company',
 'receiverId',
 'deliveryCourier',
 'expressCode',
 'expressFee',
 'courierNumber',
 'sellerRemark',
 'buyerRemark',
 'sellerFlag',
 'totalFee',
 'payment',
 'receivedPayment',
 'totalPrice',
 'totalSellPrice',
 'postFee',
 'postCode',
 'orderPayTime',
 'orderTime',
 'selfWaybillFlag',
 'waybill',
 'addressId')

#: Fields of each goodsList entry. The document spells the line id platformOlId;
#: BlankTex sends and the API returns platformOllId, which is what is used here.
GOODS_LIST_FIELDS: tuple[str, ...] = ('platformOid',
 'platformOllId',
 'goodsType',
 'title',
 'specification',
 'goodsStatus',
 'refundStatus',
 'sizeCode',
 'sizeName',
 'colorCode',
 'colorName',
 'styleCode',
 'styleName',
 'craftType',
 'num',
 'platformSpuId',
 'platformSkuId',
 'remark',
 'price',
 'sellPrice',
 'totalPrice',
 'totalSellPrice',
 'printPosition')

#: goodsLabel, flattened the way nested objects are everywhere else.
GOODS_LABEL_FIELDS: tuple[str, ...] = ('goodsLabel_productSkcId',
 'goodsLabel_skcSpecName',
 'goodsLabel_skuSpecName',
 'goodsLabel_labelCode',
 'goodsLabel_productSkuId',
 'goodsLabel_countryName',
 'goodsLabel_europeanLabelUrl')

IMAGE_LIST_FIELDS: tuple[str, ...] = ('type', 'imageUrl', 'imageCode', 'imageName')

FIELD_DICTIONARY: tuple[dict[str, str], ...] = ({'endpoint': 'General',
  'direction': 'Response',
  'level': 'envelope',
  'field': 'successful',
  'type': 'boolean',
  'required': '',
  'description': 'true = request succeeded, false = failed',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'General',
  'direction': 'Response',
  'level': 'envelope',
  'field': 'message',
  'type': 'string',
  'required': '',
  'description': 'Error or status message',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'General',
  'direction': 'Response',
  'level': 'envelope',
  'field': 'errorCode',
  'type': 'string',
  'required': '',
  'description': 'Error code (empty on success)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'General',
  'direction': 'Response',
  'level': 'envelope',
  'field': 'data',
  'type': 'any',
  'required': '',
  'description': 'Response payload (null for write operations)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformType',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Platform type. Use 15 for overseas orders.',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → platformType'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'sourcePlatformOid',
  'type': 'string',
  'required': 'Yes',
  'description': 'Source platform order number (e.g. TEMU order ID)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → sourcePlatformOid'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformOrderStatus',
  'type': 'string',
  'required': 'Yes',
  'description': 'Platform order status. Use: NOT_SHIPPED',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → platformOrderStatus'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformRefundStatus',
  'type': 'string',
  'required': 'Yes',
  'description': 'Refund status. Use: NO_REFUND',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → platformRefundStatus'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformOid',
  'type': 'string',
  'required': 'Yes',
  'description': 'Your unique order identifier (must be globally unique)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → platformOid'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'consigneeName',
  'type': 'string',
  'required': 'Yes',
  'description': 'Recipient full name',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → consigneeName'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'phone',
  'type': 'string',
  'required': 'Yes',
  'description': 'Recipient phone number',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → phone'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'address',
  'type': 'string',
  'required': 'Yes',
  'description': 'Shipping address line 1',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → address'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'addressOptional',
  'type': 'string',
  'required': 'No',
  'description': 'Shipping address line 2',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → addressOptional'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverCountry',
  'type': 'string',
  'required': 'Yes',
  'description': 'Destination country code (e.g. US)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → receiverCountry'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverProvince',
  'type': 'string',
  'required': 'Yes',
  'description': 'State / Province',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → receiverProvince'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverCity',
  'type': 'string',
  'required': 'Yes',
  'description': 'City',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → receiverCity'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverDistrict',
  'type': 'string',
  'required': 'No',
  'description': 'District / County',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → receiverDistrict'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverTown',
  'type': 'string',
  'required': 'No',
  'description': 'Town',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → receiverTown'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'company',
  'type': 'string',
  'required': 'No',
  'description': 'Recipient company name',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → company'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverId',
  'type': 'string',
  'required': 'No',
  'description': 'Recipient ID',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → receiverId'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'deliveryCourier',
  'type': 'string',
  'required': 'No',
  'description': 'Carrier name (e.g. USPS, UPS, FedEx)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → deliveryCourier'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'expressCode',
  'type': 'string',
  'required': 'No',
  'description': 'Logistics / express code',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → expressCode'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'expressFee',
  'type': 'number',
  'required': 'No',
  'description': 'Shipping fee',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → expressFee'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'courierNumber',
  'type': 'string',
  'required': 'No',
  'description': 'Tracking number',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → courierNumber'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'sellerRemark',
  'type': 'string',
  'required': 'No',
  'description': 'Seller note / remark',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → sellerRemark'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'buyerRemark',
  'type': 'string',
  'required': 'No',
  'description': 'Buyer note / remark',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → buyerRemark'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'sellerFlag',
  'type': 'string',
  'required': 'No',
  'description': 'Seller flag color (e.g. RED)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → sellerFlag'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'totalFee',
  'type': 'number',
  'required': 'No',
  'description': 'Total amount due',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → totalFee'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'payment',
  'type': 'number',
  'required': 'No',
  'description': 'Amount paid',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → payment'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receivedPayment',
  'type': 'number',
  'required': 'No',
  'description': 'Amount actually received',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → receivedPayment'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'totalPrice',
  'type': 'number',
  'required': 'No',
  'description': 'Total original price',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → totalPrice'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'totalSellPrice',
  'type': 'number',
  'required': 'No',
  'description': 'Total selling price',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → totalSellPrice'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'postFee',
  'type': 'number',
  'required': 'No',
  'description': 'Postage fee',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → postFee'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'postCode',
  'type': 'string',
  'required': 'Conditional',
  'description': 'ZIP / postal code (required for overseas orders)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → postCode'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'orderPayTime',
  'type': 'string',
  'required': 'No',
  'description': 'Payment time — format: yyyy-MM-dd HH:mm:ss',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → orderPayTime'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'orderTime',
  'type': 'string',
  'required': 'Yes',
  'description': 'Order creation time — format: yyyy-MM-dd HH:mm:ss',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → orderTime'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'selfWaybillFlag',
  'type': 'boolean',
  'required': 'Conditional',
  'description': 'true if providing your own shipping label',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → selfWaybillFlag'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'waybill',
  'type': 'string',
  'required': 'Conditional',
  'description': 'Waybill / label URL (required if selfWaybillFlag=true)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → waybill'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'addressId',
  'type': 'string',
  'required': 'Conditional',
  'description': 'Factory ship-from address ID (required if selfWaybillFlag=true)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI orders (as sent) → addressId'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'goodsList',
  'type': 'array',
  'required': 'Yes',
  'description': 'List of ordered items — see goodsList fields below',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) (one row per entry)'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'platformOid',
  'type': 'string',
  'required': 'Yes',
  'description': 'Parent order ID (same as order-level platformOid)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → platformOid'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'platformOlId',
  'type': 'string',
  'required': 'Yes',
  'description': 'Sub-order item ID — must be unique per item',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → platformOllId'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'goodsType',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Product type. Use: 1 (normal product)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → goodsType'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'title',
  'type': 'string',
  'required': 'Yes',
  'description': 'Product title / name',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → title'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'specification',
  'type': 'string',
  'required': 'No',
  'description': 'Variant description (e.g. Black/XL)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → specification'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'goodsStatus',
  'type': 'string',
  'required': 'Yes',
  'description': 'Item status. Use: NOT_SHIPPED',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → goodsStatus'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'refundStatus',
  'type': 'string',
  'required': 'Yes',
  'description': 'Refund status. Use: NO_REFUND',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → refundStatus'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'sizeCode',
  'type': 'string',
  'required': 'Yes',
  'description': 'Size code (e.g. M, L, XL) — from querySize endpoint',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → sizeCode'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'sizeName',
  'type': 'string',
  'required': 'Yes',
  'description': 'Size display name',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → sizeName'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'colorCode',
  'type': 'string',
  'required': 'Yes',
  'description': 'Color code — from queryColor endpoint',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → colorCode'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'colorName',
  'type': 'string',
  'required': 'Yes',
  'description': 'Color display name',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → colorName'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'styleCode',
  'type': 'string',
  'required': 'Yes',
  'description': 'Style/model code — from queryStyle endpoint',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → styleCode'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'styleName',
  'type': 'string',
  'required': 'Yes',
  'description': 'Style display name',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → styleName'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'craftType',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Print technique: 1 = Heat Transfer, 2 = DTG (Direct-to-Garment)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → craftType'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'num',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Quantity',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → num'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'platformSpuId',
  'type': 'string',
  'required': 'No',
  'description': 'Platform SPU ID',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → platformSpuId'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'platformSkuId',
  'type': 'string',
  'required': 'No',
  'description': 'Platform SKU ID',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → platformSkuId'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'remark',
  'type': 'string',
  'required': 'No',
  'description': 'Item remark / note',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → remark'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'price',
  'type': 'number',
  'required': 'No',
  'description': 'Original unit price',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → price'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'sellPrice',
  'type': 'number',
  'required': 'No',
  'description': 'Selling unit price',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → sellPrice'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'totalPrice',
  'type': 'number',
  'required': 'No',
  'description': 'Total original price for this item',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → totalPrice'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'totalSellPrice',
  'type': 'number',
  'required': 'No',
  'description': 'Total selling price for this item',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → totalSellPrice'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'printPosition',
  'type': 'string',
  'required': 'No',
  'description': 'Print position: 1=Front, 2=Back, 1,2=Both',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → printPosition'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'goodsLabel',
  'type': 'object',
  'required': 'No',
  'description': 'Product label and EU label info — see goodsLabel fields',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → goodsLabel_* columns'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'imageList',
  'type': 'array',
  'required': 'Yes',
  'description': 'List of images — see imageList fields below',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order line images (as sent) (one row per entry)'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].goodsLabel',
  'field': 'productSkcId',
  'type': 'string',
  'required': 'No',
  'description': 'SKU item ID. Falls back to skcId / productSkcId if skuExtCode missing.',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → goodsLabel_productSkcId'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].goodsLabel',
  'field': 'skcSpecName',
  'type': 'string',
  'required': 'No',
  'description': 'Primary attribute name (apparel only) — from productSkcSpecI18nMap.en',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → goodsLabel_skcSpecName'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].goodsLabel',
  'field': 'skuSpecName',
  'type': 'string',
  'required': 'No',
  'description': 'Secondary attribute name (apparel only) — from productSkuSpecI18nMap.en',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → goodsLabel_skuSpecName'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].goodsLabel',
  'field': 'labelCode',
  'type': 'string',
  'required': 'No',
  'description': 'Barcode / label code',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → goodsLabel_labelCode'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].goodsLabel',
  'field': 'productSkuId',
  'type': 'string',
  'required': 'No',
  'description': 'Product SKU ID',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → goodsLabel_productSkuId'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].goodsLabel',
  'field': 'countryName',
  'type': 'string',
  'required': 'No',
  'description': 'Country of origin text (e.g. Made In China)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → goodsLabel_countryName'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].goodsLabel',
  'field': 'europeanLabelUrl',
  'type': 'string',
  'required': 'No',
  'description': 'EU compliance label URL',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order lines (as sent) → goodsLabel_europeanLabelUrl'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].imageList[]',
  'field': 'type',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Image type: 1 = Print image, 2 = Mockup / effect image',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order line images (as sent) → type'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].imageList[]',
  'field': 'imageUrl',
  'type': 'string',
  'required': 'Yes',
  'description': 'Publicly accessible image URL (PNG format for print images)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order line images (as sent) → imageUrl'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].imageList[]',
  'field': 'imageCode',
  'type': 'string',
  'required': 'Yes',
  'description': 'Unique image code — different images must have different codes',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order line images (as sent) → imageCode'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[].imageList[]',
  'field': 'imageName',
  'type': 'string',
  'required': 'Yes',
  'description': 'Image name (set to the same value as imageCode)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI order line images (as sent) → imageName'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'sourcePlatformOid',
  'type': 'string',
  'required': 'Yes',
  'description': 'Source platform order number',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformOrderStatus',
  'type': 'string',
  'required': 'Yes',
  'description': 'Order status: NOT_SHIPPED / SHIPPED / CANCEL',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformOid',
  'type': 'string',
  'required': 'Yes',
  'description': 'Platform order ID',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'consigneeName',
  'type': 'string',
  'required': 'Yes',
  'description': 'Recipient name',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'phone',
  'type': 'string',
  'required': 'Yes',
  'description': 'Recipient phone',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'address',
  'type': 'string',
  'required': 'Yes',
  'description': 'Address line 1',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'addressOptional',
  'type': 'string',
  'required': 'No',
  'description': 'Address line 2',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverCountry',
  'type': 'string',
  'required': 'Yes',
  'description': 'Country code (e.g. US)',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverProvince',
  'type': 'string',
  'required': 'Yes',
  'description': 'State / Province',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverCity',
  'type': 'string',
  'required': 'Yes',
  'description': 'City',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverDistrict',
  'type': 'string',
  'required': 'No',
  'description': 'District / County',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverTown',
  'type': 'string',
  'required': 'No',
  'description': 'Town',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'receiverId',
  'type': 'string',
  'required': 'No',
  'description': 'Recipient ID',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'postCode',
  'type': 'string',
  'required': 'No',
  'description': 'ZIP / postal code (required for overseas orders)',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformRefundStatus',
  'type': 'string',
  'required': 'No',
  'description': 'Refund status',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'updateOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'goodsUpdateList',
  'type': 'array',
  'required': 'No',
  'description': 'List of items to update — same fields as placeOrder goodsList',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'preShipped',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformOid',
  'type': 'string',
  'required': 'Yes',
  'description': 'Platform order ID',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: never called by BlankTex.'},
 {'endpoint': 'queryOrderDelivery',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformOidList',
  'type': 'array',
  'required': 'Yes',
  'description': 'List of platform order IDs (max 100)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses → platformOidList'},
 {'endpoint': 'queryOrderDelivery',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'platformOid',
  'type': 'string',
  'required': '',
  'description': 'Order ID',
  'source': 'Supplier API document',
  'whereInReports': 'Order tracking and labels → platformOid'},
 {'endpoint': 'queryOrderDelivery',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'trackingNumber',
  'type': 'string',
  'required': '',
  'description': 'Shipping / tracking number',
  'source': 'Supplier API document',
  'whereInReports': 'Order tracking and labels → trackingNumber'},
 {'endpoint': 'queryOrderDelivery',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'waybillDataPath',
  'type': 'string',
  'required': '',
  'description': 'URL to download the waybill / shipping label (PDF)',
  'source': 'Supplier API document',
  'whereInReports': 'Order tracking and labels → waybillDataPath'},
 {'endpoint': 'queryOrderDelivery',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'shippingTime',
  'type': 'string',
  'required': '',
  'description': 'Shipment dispatch time',
  'source': 'Supplier API document',
  'whereInReports': 'Order tracking and labels → shippingTime'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformOidList',
  'type': 'array',
  'required': 'Yes',
  'description': 'List of platform order IDs (max 100)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses → platformOidList'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'platformOid',
  'type': 'string',
  'required': '',
  'description': 'Order ID',
  'source': 'Supplier API document',
  'whereInReports': 'Order status (per line) → platformOid'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'orderStatus',
  'type': 'integer',
  'required': '',
  'description': 'Order status code — see status codes table below',
  'source': 'Supplier API document',
  'whereInReports': 'Order status (per line) → orderStatus'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'orderStateStr',
  'type': 'string',
  'required': '',
  'description': 'Order status description',
  'source': 'Supplier API document',
  'whereInReports': 'Order status (per line) → orderStateStr'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'childOrderStatus',
  'type': 'array',
  'required': '',
  'description': 'List of sub-order / item statuses',
  'source': 'Supplier API document',
  'whereInReports': 'Order status (per line) (one row per entry; the whole array is in raw_json)'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Response',
  'level': 'data[].childOrderStatus[]',
  'field': 'platformOlId',
  'type': 'string',
  'required': '',
  'description': 'Sub-order item ID',
  'source': 'Supplier API document',
  'whereInReports': 'Order status (per line) → platformOllId'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Response',
  'level': 'data[].childOrderStatus[]',
  'field': 'goodsStatus',
  'type': 'string',
  'required': '',
  'description': 'Item status code string',
  'source': 'Supplier API document',
  'whereInReports': 'Order status (per line) → goodsStatus'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Response',
  'level': 'data[].childOrderStatus[]',
  'field': 'goodsStatusStr',
  'type': 'string',
  'required': '',
  'description': 'Item status description',
  'source': 'Supplier API document',
  'whereInReports': 'Order status (per line) → goodsStatusStr'},
 {'endpoint': 'queryProduct',
  'direction': 'Request',
  'level': 'body',
  'field': 'pageIndex',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Page number (default: 1)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryProduct',
  'direction': 'Request',
  'level': 'body',
  'field': 'pageSize',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Items per page (default: 1000)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'productCode',
  'type': 'string',
  'required': '',
  'description': 'Product code',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue products → productCode'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'styleCode',
  'type': 'string',
  'required': '',
  'description': 'Style / model code',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue products → styleCode'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'colorCode',
  'type': 'string',
  'required': '',
  'description': 'Color code',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue products → colorCode'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'sizeCode',
  'type': 'string',
  'required': '',
  'description': 'Size code',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue products → sizeCode'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'unitType',
  'type': 'integer',
  'required': '',
  'description': 'Measurement system: 1 = cm/kg, 2 = in/lbs',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue products → unitType'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'weight',
  'type': 'string',
  'required': '',
  'description': 'Product weight',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue products → weight'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'size',
  'type': 'string',
  'required': '',
  'description': 'Dimensions: length × width × height',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue products → size'},
 {'endpoint': 'queryStyle',
  'direction': 'Request',
  'level': 'body',
  'field': 'pageIndex',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Page number (default: 1)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryStyle',
  'direction': 'Request',
  'level': 'body',
  'field': 'pageSize',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Items per page (default: 1000)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryStyle',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'styleName',
  'type': 'string',
  'required': '',
  'description': 'Style display name',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue styles → styleName'},
 {'endpoint': 'queryStyle',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'styleCode',
  'type': 'string',
  'required': '',
  'description': 'Style code (use in orders)',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue styles → styleCode'},
 {'endpoint': 'queryStyle',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'craftType',
  'type': 'string',
  'required': '',
  'description': 'Supported craft types: 1=Heat Transfer, 2=DTG. May be comma-separated (e.g. '
                 "'1,2')",
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue styles → craftType'},
 {'endpoint': 'queryStyle',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'images',
  'type': 'string',
  'required': '',
  'description': 'JSON array string of style preview image URLs',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue styles → images'},
 {'endpoint': 'queryColor',
  'direction': 'Request',
  'level': 'body',
  'field': 'pageIndex',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Page number (default: 1)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryColor',
  'direction': 'Request',
  'level': 'body',
  'field': 'pageSize',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Items per page (default: 1000)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryColor',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'colorName',
  'type': 'string',
  'required': '',
  'description': 'Color display name',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue colours → colorName'},
 {'endpoint': 'queryColor',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'colorCode',
  'type': 'string',
  'required': '',
  'description': 'Color code (use in orders)',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue colours → colorCode'},
 {'endpoint': 'querySize',
  'direction': 'Request',
  'level': 'body',
  'field': 'pageIndex',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Page number (default: 1)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'querySize',
  'direction': 'Request',
  'level': 'body',
  'field': 'pageSize',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Items per page (default: 1000)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'querySize',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'sizeName',
  'type': 'string',
  'required': '',
  'description': 'Size display name',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue sizes → sizeName'},
 {'endpoint': 'querySize',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'sizeCode',
  'type': 'string',
  'required': '',
  'description': 'Size code (use in orders)',
  'source': 'Supplier API document',
  'whereInReports': 'Catalogue sizes → sizeCode'},
 {'endpoint': 'queryShipAddress',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'id',
  'type': 'long',
  'required': '',
  'description': 'Internal ID',
  'source': 'Supplier API document',
  'whereInReports': 'Factory ship-from addresses → id'},
 {'endpoint': 'queryShipAddress',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'country',
  'type': 'string',
  'required': '',
  'description': 'Country',
  'source': 'Supplier API document',
  'whereInReports': 'Factory ship-from addresses → country'},
 {'endpoint': 'queryShipAddress',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'province',
  'type': 'string',
  'required': '',
  'description': 'State / Province',
  'source': 'Supplier API document',
  'whereInReports': 'Factory ship-from addresses → province'},
 {'endpoint': 'queryShipAddress',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'city',
  'type': 'string',
  'required': '',
  'description': 'City',
  'source': 'Supplier API document',
  'whereInReports': 'Factory ship-from addresses → city'},
 {'endpoint': 'queryShipAddress',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'address',
  'type': 'string',
  'required': '',
  'description': 'Full street address',
  'source': 'Supplier API document',
  'whereInReports': 'Factory ship-from addresses → address'},
 {'endpoint': 'queryShipAddress',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'addressId',
  'type': 'string',
  'required': '',
  'description': 'Address ID — use this value in order requests',
  'source': 'Supplier API document',
  'whereInReports': 'Factory ship-from addresses → addressId'},
 {'endpoint': 'closeOrder',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformOid',
  'type': 'string',
  'required': 'Yes',
  'description': 'Platform order ID to close',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: BlankTex does not keep the requests it sends here. The same '
                    'values as they stand now are in DIGI Orders and Order detail.'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Request',
  'level': 'body',
  'field': 'productCodeList',
  'type': 'array',
  'required': 'Yes',
  'description': 'List of product codes (max 10)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses → productCodeList'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'productCode',
  'type': 'string',
  'required': '',
  'description': 'Product code',
  'source': 'Supplier API document',
  'whereInReports': 'Which factory ships which product → productCode'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'addressList',
  'type': 'array',
  'required': '',
  'description': 'List of available factory addresses for this product — see address fields below',
  'source': 'Supplier API document',
  'whereInReports': 'Which factory ships which product (one row per entry; the whole array is in '
                    'raw_json)'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Response',
  'level': 'data[].addressList[]',
  'field': 'id',
  'type': 'long',
  'required': '',
  'description': 'Internal address ID',
  'source': 'Supplier API document',
  'whereInReports': 'Which factory ships which product → id'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Response',
  'level': 'data[].addressList[]',
  'field': 'country',
  'type': 'string',
  'required': '',
  'description': 'Country code',
  'source': 'Supplier API document',
  'whereInReports': 'Which factory ships which product → country'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Response',
  'level': 'data[].addressList[]',
  'field': 'province',
  'type': 'string',
  'required': '',
  'description': 'State / Province',
  'source': 'Supplier API document',
  'whereInReports': 'Which factory ships which product → province'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Response',
  'level': 'data[].addressList[]',
  'field': 'city',
  'type': 'string',
  'required': '',
  'description': 'City',
  'source': 'Supplier API document',
  'whereInReports': 'Which factory ships which product → city'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Response',
  'level': 'data[].addressList[]',
  'field': 'address',
  'type': 'string',
  'required': '',
  'description': 'Full street address',
  'source': 'Supplier API document',
  'whereInReports': 'Which factory ships which product → address'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Response',
  'level': 'data[].addressList[]',
  'field': 'addressId',
  'type': 'string',
  'required': '',
  'description': 'Address ID to use in order placement',
  'source': 'Supplier API document',
  'whereInReports': 'Which factory ships which product → addressId'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformOidList',
  'type': 'array',
  'required': 'Yes',
  'description': 'List of platform order IDs (max 100)',
  'source': 'Supplier API document',
  'whereInReports': 'DIGI API responses → platformOidList'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'platformOid',
  'type': 'string',
  'required': '',
  'description': 'Order ID',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → platformOid'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'orderStatus',
  'type': 'integer',
  'required': '',
  'description': 'Order status code',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → orderStatus'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'goodsTotalQty',
  'type': 'integer',
  'required': '',
  'description': 'Total item quantity',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → goodsTotalQty'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'platformOrderStatus',
  'type': 'string',
  'required': '',
  'description': 'Platform order status',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → platformOrderStatus'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'platformRefundStatus',
  'type': 'string',
  'required': '',
  'description': 'Platform refund status',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → platformRefundStatus'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'platformShopCode',
  'type': 'string',
  'required': '',
  'description': 'Shop code',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → platformShopCode'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'platformShopName',
  'type': 'string',
  'required': '',
  'description': 'Shop name',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → platformShopName'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'platformType',
  'type': 'integer',
  'required': '',
  'description': 'Platform type',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → platformType'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'deliveryCourier',
  'type': 'string',
  'required': '',
  'description': 'Carrier name',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → deliveryCourier'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'expressCode',
  'type': 'string',
  'required': '',
  'description': 'Express / logistics code',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → expressCode'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'courierNumber',
  'type': 'string',
  'required': '',
  'description': 'Tracking number',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → courierNumber'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'consigneeName',
  'type': 'string',
  'required': '',
  'description': 'Recipient name',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → consigneeName'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'phone',
  'type': 'string',
  'required': '',
  'description': 'Recipient phone',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → phone'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'address',
  'type': 'string',
  'required': '',
  'description': 'Address line 1',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → address'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'addressOptional',
  'type': 'string',
  'required': '',
  'description': 'Address line 2',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → addressOptional'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'receiverCountry',
  'type': 'string',
  'required': '',
  'description': 'Country',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → receiverCountry'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'receiverProvince',
  'type': 'string',
  'required': '',
  'description': 'State / Province',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → receiverProvince'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'receiverCity',
  'type': 'string',
  'required': '',
  'description': 'City',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → receiverCity'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'postCode',
  'type': 'string',
  'required': '',
  'description': 'ZIP / Postal code',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → postCode'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'orderTime',
  'type': 'string',
  'required': '',
  'description': 'Order creation time',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → orderTime'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'preShippingTime',
  'type': 'string',
  'required': '',
  'description': 'Pre-shipping time',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → preShippingTime'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'shippingTime',
  'type': 'string',
  'required': '',
  'description': 'Actual dispatch / shipping time',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → shippingTime'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'addressId',
  'type': 'string',
  'required': '',
  'description': 'Factory ship-from address ID',
  'source': 'Supplier API document',
  'whereInReports': 'Order detail → addressId'},
 {'endpoint': 'updatePrintImage',
  'direction': 'Request',
  'level': 'body',
  'field': 'platformOid',
  'type': 'string',
  'required': 'Yes',
  'description': 'Platform order ID',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: never called by BlankTex. Images as first sent are in DIGI '
                    'order line images (as sent).'},
 {'endpoint': 'updatePrintImage',
  'direction': 'Request',
  'level': 'body',
  'field': 'goodsList',
  'type': 'array',
  'required': 'Yes',
  'description': 'List of items to update images for',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: never called by BlankTex. Images as first sent are in DIGI '
                    'order line images (as sent).'},
 {'endpoint': 'updatePrintImage',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'platformOid',
  'type': 'string',
  'required': 'Yes',
  'description': 'Parent order ID',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: never called by BlankTex. Images as first sent are in DIGI '
                    'order line images (as sent).'},
 {'endpoint': 'updatePrintImage',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'platformOlId',
  'type': 'string',
  'required': 'Yes',
  'description': 'Sub-order item ID',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: never called by BlankTex. Images as first sent are in DIGI '
                    'order line images (as sent).'},
 {'endpoint': 'updatePrintImage',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'imageList',
  'type': 'array',
  'required': 'Yes',
  'description': 'New image list — same structure as in placeOrder',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: never called by BlankTex. Images as first sent are in DIGI '
                    'order line images (as sent).'},
 {'endpoint': 'updatePrintImage',
  'direction': 'Request',
  'level': 'goodsList[].imageList[]',
  'field': 'type',
  'type': 'integer',
  'required': 'Yes',
  'description': 'Image type: 1=Print image, 2=Mockup/effect image',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: never called by BlankTex. Images as first sent are in DIGI '
                    'order line images (as sent).'},
 {'endpoint': 'updatePrintImage',
  'direction': 'Request',
  'level': 'goodsList[].imageList[]',
  'field': 'imageUrl',
  'type': 'string',
  'required': 'Yes',
  'description': 'Image URL',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: never called by BlankTex. Images as first sent are in DIGI '
                    'order line images (as sent).'},
 {'endpoint': 'updatePrintImage',
  'direction': 'Request',
  'level': 'goodsList[].imageList[]',
  'field': 'imageCode',
  'type': 'string',
  'required': 'Yes',
  'description': 'Unique image code',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: never called by BlankTex. Images as first sent are in DIGI '
                    'order line images (as sent).'},
 {'endpoint': 'updatePrintImage',
  'direction': 'Request',
  'level': 'goodsList[].imageList[]',
  'field': 'imageName',
  'type': 'string',
  'required': 'Yes',
  'description': 'Image name (same as imageCode)',
  'source': 'Supplier API document',
  'whereInReports': 'Not recorded: never called by BlankTex. Images as first sent are in DIGI '
                    'order line images (as sent).'},
 {'endpoint': 'General',
  'direction': 'Response',
  'level': 'envelope',
  'field': 'traceId',
  'type': 'string',
  'required': '',
  'description': 'Request trace id, returned on every call',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'General',
  'direction': 'Response',
  'level': 'envelope',
  'field': 'success',
  'type': 'boolean',
  'required': '',
  'description': 'Some responses use this instead of successful',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryColor',
  'direction': 'Response',
  'level': 'data',
  'field': 'pageIndex',
  'type': 'integer',
  'required': '',
  'description': 'Page number of this response',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryColor',
  'direction': 'Response',
  'level': 'data',
  'field': 'pageSize',
  'type': 'integer',
  'required': '',
  'description': 'Page size of this response',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryColor',
  'direction': 'Response',
  'level': 'data',
  'field': 'total',
  'type': 'string',
  'required': '',
  'description': 'Total records available, as a string',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryColor',
  'direction': 'Response',
  'level': 'data',
  'field': 'records',
  'type': 'array',
  'required': '',
  'description': 'The records on this page',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data',
  'field': 'pageIndex',
  'type': 'integer',
  'required': '',
  'description': 'Page number of this response',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data',
  'field': 'pageSize',
  'type': 'integer',
  'required': '',
  'description': 'Page size of this response',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data',
  'field': 'total',
  'type': 'string',
  'required': '',
  'description': 'Total records available, as a string',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data',
  'field': 'records',
  'type': 'array',
  'required': '',
  'description': 'The records on this page',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'querySize',
  'direction': 'Response',
  'level': 'data',
  'field': 'pageIndex',
  'type': 'integer',
  'required': '',
  'description': 'Page number of this response',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'querySize',
  'direction': 'Response',
  'level': 'data',
  'field': 'pageSize',
  'type': 'integer',
  'required': '',
  'description': 'Page size of this response',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'querySize',
  'direction': 'Response',
  'level': 'data',
  'field': 'total',
  'type': 'string',
  'required': '',
  'description': 'Total records available, as a string',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'querySize',
  'direction': 'Response',
  'level': 'data',
  'field': 'records',
  'type': 'array',
  'required': '',
  'description': 'The records on this page',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryStyle',
  'direction': 'Response',
  'level': 'data',
  'field': 'pageIndex',
  'type': 'integer',
  'required': '',
  'description': 'Page number of this response',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryStyle',
  'direction': 'Response',
  'level': 'data',
  'field': 'pageSize',
  'type': 'integer',
  'required': '',
  'description': 'Page size of this response',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryStyle',
  'direction': 'Response',
  'level': 'data',
  'field': 'total',
  'type': 'string',
  'required': '',
  'description': 'Total records available, as a string',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryStyle',
  'direction': 'Response',
  'level': 'data',
  'field': 'records',
  'type': 'array',
  'required': '',
  'description': 'The records on this page',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI API responses'},
 {'endpoint': 'queryStyle',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'priceMode',
  'type': 'integer',
  'required': '',
  'description': 'Pricing mode; 1 is the only value seen',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Catalogue styles → priceMode'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'renderingId',
  'type': 'string',
  'required': '',
  'description': 'Rendering template id',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Catalogue products → renderingId'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'renderingName',
  'type': 'string',
  'required': '',
  'description': 'Rendering template name',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Catalogue products → renderingName'},
 {'endpoint': 'queryProduct',
  'direction': 'Response',
  'level': 'data.records[]',
  'field': 'styleImg',
  'type': 'string',
  'required': '',
  'description': 'JSON array string of style image URLs',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Catalogue products → styleImg'},
 {'endpoint': 'queryShipAddress',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'addressAlias',
  'type': 'string',
  'required': '',
  'description': 'Short name for the address',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Factory ship-from addresses → addressAlias'},
 {'endpoint': 'queryShipAddress',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'enabled',
  'type': 'boolean',
  'required': '',
  'description': 'Whether the address can be used',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Factory ship-from addresses → enabled'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Response',
  'level': 'data[].addressList[]',
  'field': 'addressAlias',
  'type': 'string',
  'required': '',
  'description': 'Short name for the address',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Which factory ships which product → addressAlias'},
 {'endpoint': 'queryProductShipAddress',
  'direction': 'Response',
  'level': 'data[].addressList[]',
  'field': 'enabled',
  'type': 'boolean',
  'required': '',
  'description': 'Whether the address can be used',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Which factory ships which product → enabled'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'reason',
  'type': 'string',
  'required': '',
  'description': 'Why an order was rejected, when it was',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Order status (per line) → reason'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Response',
  'level': 'data[].childOrderStatus[]',
  'field': 'platformOllId',
  'type': 'string',
  'required': '',
  'description': 'The line id as the API actually spells it (the document writes platformOlId)',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Order status (per line) → platformOllId'},
 {'endpoint': 'queryOrderStatus',
  'direction': 'Response',
  'level': 'data[].childOrderStatus[]',
  'field': 'productMessage',
  'type': 'string',
  'required': '',
  'description': 'Supplier note on the line',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Order status (per line) → productMessage'},
 {'endpoint': 'queryOrderDelivery',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'express',
  'type': 'string',
  'required': '',
  'description': 'Carrier name',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Order tracking and labels → express'},
 {'endpoint': 'queryOrderInfo',
  'direction': 'Response',
  'level': 'data[]',
  'field': 'id',
  'type': 'string',
  'required': '',
  'description': "The supplier's internal order id",
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'Order detail → id'},
 {'endpoint': 'placeOrder',
  'direction': 'Request',
  'level': 'goodsList[]',
  'field': 'platformOllId',
  'type': 'string',
  'required': '',
  'description': 'The line id as BlankTex actually sends it (the document writes platformOlId)',
  'source': 'Observed in live responses (not in the document)',
  'whereInReports': 'DIGI order lines (as sent) → platformOllId'},
 {'endpoint': 'General',
  'direction': 'Request',
  'level': 'header',
  'field': 'secretKey',
  'type': 'string',
  'required': 'Yes',
  'description': 'API secret key, sent as a header',
  'source': 'Supplier API document',
  'whereInReports': 'Never recorded: it is a credential.'},
 {'endpoint': 'General',
  'direction': 'Request',
  'level': 'header',
  'field': 'sign',
  'type': 'string',
  'required': 'Yes',
  'description': 'MD5 of the request body and the secret key, sent as a header',
  'source': 'Supplier API document',
  'whereInReports': 'Never recorded: it is a credential.'})
